package com.opninterviewservice.testapp.restapi.apistub


//This File Created at 24.10.2020 12:59.
const val PEOPLE_LIST_JSON = """[
{"id": "1",
"firstName": "one"},
{"id": "2",
"firstName": "two"},
{"id": "3",
"firstName": "three"},
{"id": "4",
"firstName": "four"},
{"id": "5",
"firstName": "fife"},
{"id": "6",
"firstName": "six"},
{"id": "7",
"firstName": "seven"},
{"id": "8",
"firstName": "eight"},
{"id": "9",
"firstName": "nine"},
{"id": "10",
"firstName": "ten"}
]
"""

const val PERSON_INFO_LIST_JSON = """[
{"id": "1",
"firstName": "one",
"lastName": "oneLast",
"age": 1,
"country":"oneCountry"},
{"id": "2",
"firstName": "two",
"lastName": "twoLast",
"age": 2,
"country":"twoCountry"},
{"id": "3",
"firstName": "three",
"lastName": "threeLast",
"age": 3,
"country":"threeCountry"},
{"id": "4",
"firstName": "four",
"lastName": "fourLast",
"age": 4,
"country":"fourCountry"},
{"id": "5",
"firstName": "fife",
"lastName": "fifeLast",
"age": 5,
"country":"fifeCountry"},
{"id": "6",
"firstName": "six",
"lastName": "sixLast",
"age": 6,
"country":"sixCountry"},
{"id": "7",
"firstName": "seven",
"lastName": "sevenLast",
"age": 7,
"country":"sevenCountry"},
{"id": "8",
"firstName": "eight",
"lastName": "eightLast",
"age": 8,
"country":"eightCountry"},
{"id": "9",
"firstName": "nine",
"lastName": "nineLast",
"age": 9,
"country":"nineCountry"},
{"id": "10",
"firstName": "ten",
"lastName": "tenLast",
"age": 10,
"country":"tenCountry"}
]
"""